apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: poc-vault-secret
  data:
  - secretKey: DB_USER
    remoteRef:
      key: poc-vault/database
      property: DB_USER
  - secretKey: DB_PASS
    remoteRef:
      key: poc-vault/database
      property: DB_PASS