name: deploy
run-name: ${{ github.actor }}
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and Publish the Docker image
      run: | 
        docker login ${DOCKER_REGISTRY} -u ${GB_USER} -p ${{ secrets.GH_TOKEN }}
        docker build . --file Dockerfile --tag ${DOCKER_REGISTRY}/${GB_USER}/poc-vault:latest
        docker push ${DOCKER_REGISTRY}/${GB_USER}/poc-vault:latest
      env:
        DOCKER_REGISTRY: ghcr.io
        GB_USER: thiagomoreirag
